version: "3.7"

services:
    api:
        image: api:1.0.0
        build: .
        ports:
            - "8081:8081"
        environment:
            DATABASE_URL: jdbc:mysql://mysqldb:3306/seller?createDatabaseIfNotExist=true&serverTimezone=UTC
            DATABASE_USERNAME: admin
            DATABASE_PASSWORD: 1234
        restart: always
        depends_on:
            - mysqldb

    mysqldb:
        image: mysql:8.0.33
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: seller
            MYSQL_USER: admin
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 1234
